### PR TITLE
Csv test workflows

### PR DESCRIPTION
**Pull request by tezansahu**
## Description
Created a function to submit multiple workflows, the specifications of which can be obtained from CSV file. Incorporated related tests & documentation changes

## Motivation and Context
This function could be the first step towards creating an automated test bed & generate insights about a certain predefined set of workflow configurations that the maintainers of PEcAn would want to pass before any new change or release. This will provide a way to monitor which workflows passed & failed between 2 successive such tests, & hence allows maintainers to hunt for the potential errors in a very limited timeframe or limited amount of codebase (only those files which have been modified between 2 successive tests).

Currently, we are able to only submit a set of workflows defined in a CSV, but in future this can be extended to poll for the completion of these workflows & generate more insights (like the time taken for execution, etc), documented in another CSV for easier analysis.

## Review Time Estimate

- [x] Immediately
- [ ] Within one week
- [ ] When possible
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ashiklom** [comment]
This looks great! Excellent work, @tezansahu! 👍 to keeping this a part of the API. We can always add a thin Shiny layer around it later if we want.

Once this is merged, I think the most important next step should be to get this working on GH Actions. I've messed around with this a bit, but it was hampered by the fact that our Docker Hub images didn't yet include the latest API images. But once those are updated, I think something like my [YAML config](https://github.com/ashiklom/pecan/blob/local-develop/.github/workflows/integration.yml) combined with the R utilities here should work.

**Comment by tezansahu** [comment]
Thank a lot @ashiklom. The current implementation of this function in `rpecanapi` actually supports only SIPNET models (not ED2) because of the lack of data about `inputs` (like `veg`, `soil` & `thsum`, which are necessary for ED2 model) in the CSV files currently. Hence, although ED2 based workflows get submitted successfully, we can't expect them to be executed without error(s) at this stage. However, if we manage to somehow include the above mentioned details in the CSV file in a generic sense (like, having 3 columns called `veg`, `soil` & `thsum`, with corresponding IDs for ED2 models, while being blank for SIPNET or other models) could help sort this issue.

Also, I was browsing through https://github.com/ashiklom/pecan/blob/local-develop/base/workflow/inst/default_tests.csv, where you seem to have allowed multiple PFTs separated by "|". In this PR currently, I have just assumed ` PFT in the pft column, but can modify it to incorporate multiple PFTs delimited by "|" if you want so.

Do let me know about the above to 2 points so that I could add those to this PR before merging

**Comment by robkooper** [comment]
Do we want to use a json or xml file instead for the tests. I know csv is easy, but it seems harder to add more complex like pfts.

```
[
	{
		"comment": "SIPNET Demo 1",
		"model": "SIPNET",
		"reversion": "r136",
		"met": "AmerifluxLBL",
		"site_id": 772,
		"pft": [
			"temperate.coniferou"
		],
		"start_date": "2003-01-01",
		"end_date": "2003-12-31",
		"sensitivity": {
		},
		"ensemble": {
			"size": 1,
		}
	},
	{
		"comment": "SIPNET Demo 2",
		"model": "SIPNET",
		"reversion": "r136",
		"met": "AmerifluxLBL",
		"site_id": 772,
		"pft": [
			"temperate.coniferou"
		],
		"start_date": "2003-01-01",
		"end_date": "2003-12-31",
		"sensitivity": {
			"variable": [
				"GPP"
			],
			"quantiles": [
				-1, 1
			]
		},
		"ensemble": {
			"size": 10,
		}
	}
]
```

**Comment by tezansahu** [comment]
This is actually a much better thought in my opinion. But yeah, it's kind of a trade off between the functionality that we try to achieve & the ease/compactness of representing information. So, it would be nice to get the opinions of @ashiklom @infotroph @mdietze on this proposal of a JSON representation as well.

**Comment by ashiklom** [comment]
Personally, I'd probably stick with CSV because it's the easiest to edit and translate into a pass-fail matrix. JSON introduces a third format new PEcAn users would have to learn. For XML, rather than having a special format, we might as well just have a folder of XML test files (kind of like we do now). Though because XML is a pain to edit by hand, someone would just end up writing a script to generate a bunch of XMLs from a CSV table or similar anyway.

**Review by robkooper — APPROVED** [review]

**Pull request merged**
